export default {
	// font svg
	alienFont: 'http://svg-support.boardgamereview.cn/alienFont.png',
	alienFont_d: 'http://svg-support.boardgamereview.cn/alienFont_d.png',
	ufoFont: 'http://svg-support.boardgamereview.cn/ufoFont.png',
	ufoFont_d: 'http://svg-support.boardgamereview.cn/ufoFont_b.png',
	monsterFont: 'http://svg-support.boardgamereview.cn/monsterFont.png',
	area51Font: 'http://svg-support.boardgamereview.cn/area-51Font.png',
	logonFont: 'http://svg-support.boardgamereview.cn/logonFont.png',
	logonFont_d: 'http://svg-support.boardgamereview.cn/logonFont_d.png',
	nobodyFont: 'http://svg-support.boardgamereview.cn/nobodyFont.png',
	nobodyFont_d: 'http://svg-support.boardgamereview.cn/nobodyFont_d.png',
	emptyBoxSvg: 'http://svg-support.boardgamereview.cn/package.png',
	chatBubbleWhite: 'http://svg-support.boardgamereview.cn/speech-bubble-white.png',
	chatBubbleBlack: 'http://svg-support.boardgamereview.cn/speech-bubble-black.png',
	brainFont_w: 'http://svg-support.boardgamereview.cn/artificial-intelligence.png',
  quoteFont: 'http://svg-support.boardgamereview.cn/quotes.png',
	topicTemplate: 'http://svg-support.boardgamereview.cn/template.png',
	// color svg
	dice: 'http://svg-support.boardgamereview.cn/dice.png',
	dices: 'http://svg-support.boardgamereview.cn/dices.png',
	monster: 'http://svg-support.boardgamereview.cn/monster.png',
	innocent: 'http://svg-support.boardgamereview.cn/peopleImnot.png',
	apologize: 'http://svg-support.boardgamereview.cn/depressed.png',
	question: 'http://svg-support.boardgamereview.cn/question.png',
	gotGame: 'http://svg-support.boardgamereview.cn/crown.png',
	error: 'http://svg-support.boardgamereview.cn/error.png',
	checked: 'http://svg-support.boardgamereview.cn/checked.png',
	warning: 'http://svg-support.boardgamereview.cn/warning.png',
	amazonSvg: 'http://svg-support.boardgamereview.cn/amazon.png',
	reportSvg: 'http://svg-support.boardgamereview.cn/decision-making.png',
	editSvg: 'http://svg-support.boardgamereview.cn/pencil.png',
	medalSvg: 'http://svg-support.boardgamereview.cn/016-medal.png',
	chartSvg: 'http://svg-support.boardgamereview.cn/charts.png',
	people: 'http://svg-support.boardgamereview.cn/018-people.png',
	sandTimer: 'http://svg-support.boardgamereview.cn/hourglass.png',
	linkSvg: 'http://svg-support.boardgamereview.cn/link.png',
	switchSvg: 'http://svg-support.boardgamereview.cn/power-button.png',
	quoteSvg: 'http://svg-support.boardgamereview.cn/quotation.png',
	chatBubbleColor: 'http://svg-support.boardgamereview.cn/speech-bubble-color.png',
	messageSvg: 'http://svg-support.boardgamereview.cn/email.png',
	brokenImage: 'http://svg-support.boardgamereview.cn/brokenphoto.png',
	photoFrame: 'http://svg-support.boardgamereview.cn/photograph.png',
	chatSleep: 'http://svg-support.boardgamereview.cn/tentDark.png',
	repeatGame: 'http://svg-support.boardgamereview.cn/satisfied.png',
	errorLink: 'http://svg-support.boardgamereview.cn/research.png',
	geekCloud: 'http://svg-support.boardgamereview.cn/geek.png',
	aphorismFormat: 'http://svg-support.boardgamereview.cn/feather-pen.png',
	awardSvg: 'http://svg-support.boardgamereview.cn/emblem.png',
	surprised: 'http://svg-support.boardgamereview.cn/explosion.png',
	surprisedR: 'http://svg-support.boardgamereview.cn/explosionR.png',
	runaway: 'http://svg-support.boardgamereview.cn/fart.png',
	runawayR: 'http://svg-support.boardgamereview.cn/fartR.png',
	dropsL: 'http://svg-support.boardgamereview.cn/dropsL.png',
	dropsR: 'http://svg-support.boardgamereview.cn/dropsR.png',
	drops: 'http://svg-support.boardgamereview.cn/drops.png',
	addImage: 'http://svg-support.boardgamereview.cn/choseHeader.png',
	loader: 'http://svg-support.boardgamereview.cn/refresh.png',
	pushPin: 'http://svg-support.boardgamereview.cn/push-pin.png',
	// game bookmark svg
	hexagonGray: 'http://svg-support.boardgamereview.cn/hexagonGray.png',
	hexagonGold: 'http://svg-support.boardgamereview.cn/hexagonGold.png',
	hexagonGreen: 'http://svg-support.boardgamereview.cn/hexagonGreen.png',
	hexagonOrange: 'http://svg-support.boardgamereview.cn/hexagonOrange.png',
	hexagonBlue: 'http://svg-support.boardgamereview.cn/hexagonBlue.png',
	box3D: 'http://svg-support.boardgamereview.cn/box.png',
	pacman3D: 'http://svg-support.boardgamereview.cn/pacman.png',
	heart3D: 'http://svg-support.boardgamereview.cn/heart.png',
	chest3D: 'http://svg-support.boardgamereview.cn/chest.png',
	flag3D: 'http://svg-support.boardgamereview.cn/flag.png',
	// user achivements badge
	interactioner: 'http://svg-support.boardgamereview.cn/003-chevron-2.png',
	supporter: 'http://svg-support.boardgamereview.cn/002-chevron.png',
	curator: 'http://svg-support.boardgamereview.cn/001-chevron-1.png',
	admin: 'http://svg-support.boardgamereview.cn/adminBadge.png',
	noPrice: 'http://svg-support.boardgamereview.cn/price-tag.png',
	// countrys flags
	cn: 'http://svg-support.boardgamereview.cn/008-china.png',
	en: 'http://svg-support.boardgamereview.cn/006-united-kingdom.png',
	us: 'http://svg-support.boardgamereview.cn/007-united-states.png',
	ja: 'http://svg-support.boardgamereview.cn/009-japan.png',
	tw: 'http://svg-support.boardgamereview.cn/005-taiwan.png',
	hk: 'http://svg-support.boardgamereview.cn/004-hong-kong.png',
	kr: 'http://svg-support.boardgamereview.cn/003-south-korea.png',
	de: 'http://svg-support.boardgamereview.cn/002-germany.png',
	fr: 'http://svg-support.boardgamereview.cn/001-france.png',
	// sale part
	coupon: 'http://svg-support.boardgamereview.cn/coupon.png',
	saleCat: 'http://svg-support.boardgamereview.cn/sales.png',
	couponBack: 'http://svg-support.boardgamereview.cn/coupon_back.png',
	soldOut: 'http://svg-support.boardgamereview.cn/soldout.png',
	lockSvg: 'http://svg-support.boardgamereview.cn/locked.png',
	unlockSvg: 'http://svg-support.boardgamereview.cn/unlocked.png',
	shopOpen: 'http://svg-support.boardgamereview.cn/open.png',
	shopClose: 'http://svg-support.boardgamereview.cn/close.png',
	startSvg: 'http://svg-support.boardgamereview.cn/forward.png',
	step1: 'https://static-svg.boardgamereview.cn/step1.png',
	step2: 'https://static-svg.boardgamereview.cn/step2.png',
	step3: 'https://static-svg.boardgamereview.cn/step3.png',
	step4: 'https://static-svg.boardgamereview.cn/step4.png',
	chestOpen: 'http://svg-support.boardgamereview.cn/gold.png',
	// main logo
	logo_s: 'https://www.boardgamereview.cn/logoN.png?imageMogr2/auto-orient/thumbnail/56x/blur/1x0/quality/100',
	logo_m:
		'https://www.boardgamereview.cn/logoN.png?imageMogr2/auto-orient/thumbnail/128x/interlace/1/blur/1x0/quality/100',
	logo_l: 'https://www.boardgamereview.cn/logoN.png?imageMogr2/auto-orient/thumbnail/256x/blur/1x0/quality/75',
	logo_w_s: 'https://www.boardgamereview.cn/logoW.png?imageMogr2/auto-orient/thumbnail/56x/blur/1x0/quality/100',
	logo_w_m:
		'https://www.boardgamereview.cn/logoW.png?imageMogr2/auto-orient/thumbnail/128x/interlace/1/blur/1x0/quality/100'
};
